# Generated by Django 5.1.2 on 2024-10-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=20)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('t_max', models.CharField(max_length=20)),
                ('t_min', models.CharField(max_length=20)),
                ('current_t', models.CharField(max_length=20)),
                ('wind', models.CharField(max_length=200)),
                ('humidity', models.CharField(max_length=20)),
                ('pop', models.CharField(max_length=20)),
                ('pressure', models.CharField(max_length=20)),
                ('feels_like', models.CharField(max_length=20)),
            ],
        ),
    ]
