# Generated by Django 5.1.2 on 2024-10-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_city_remove_currentweather_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritecities',
            name='city',
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='favouritecities',
            name='user',
        ),
        migrations.DeleteModel(
            name='Forecast',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='FavouriteCities',
        ),
    ]
