# Generated by Django 5.1.2 on 2024-10-22 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_favouritecities_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('lat', models.CharField(max_length=200)),
                ('lng', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.city'),
        ),
        migrations.CreateModel(
            name='FavouriteCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_max', models.CharField(max_length=20)),
                ('t_min', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=20)),
                ('date', models.DateTimeField(max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.city')),
            ],
        ),
    ]
