# Generated by Django 5.1.2 on 2024-10-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_city_alter_currentweather_city_favouritecities_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='currentweather',
            options={'verbose_name': 'CurrentWeathers'},
        ),
        migrations.AlterModelOptions(
            name='favouritecities',
            options={'verbose_name': 'FavouriteCities'},
        ),
        migrations.AlterModelOptions(
            name='forecast',
            options={'verbose_name': 'Forecasts'},
        ),
    ]
