# Generated by Django 5.1.2 on 2024-10-23 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_city_options_alter_currentweather_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='currentweather',
            options={'verbose_name_plural': 'CurrentWeathers'},
        ),
        migrations.AlterModelOptions(
            name='favouritecities',
            options={'verbose_name_plural': 'FavouriteCities'},
        ),
        migrations.AlterModelOptions(
            name='forecast',
            options={'verbose_name_plural': 'Forecasts'},
        ),
    ]
