# Generated by Django 5.1.2 on 2024-11-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_city_options_alter_currentweather_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
