# Generated by Django 5.1.2 on 2024-11-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_city_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
