# Generated by Django 5.1.2 on 2024-11-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_city_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentweather',
            name='icon',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
