# Generated by Django 5.1.2 on 2024-11-08 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_currentweather_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='lng',
            new_name='lon',
        ),
    ]
