# Generated by Django 5.1.2 on 2024-11-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_rename_lng_city_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentweather',
            name='desc',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
