# Generated by Django 5.1.2 on 2024-12-09 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_currentweather_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=20)),
                ('date', models.DateTimeField(max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.city')),
            ],
            options={
                'verbose_name_plural': 'Hourlies',
            },
        ),
    ]
